// Run against Vite with PLAYWRIGHT_MODULE pointing to a Playwright installation.
import { pathToFileURL } from 'node:url';
const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE ?? '/tmp/voxelon-map-check/node_modules/playwright/index.mjs').href);
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
const page = await browser.newPage({viewport:{width:1360,height:950}});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.route('**/atlas-check',route=>route.fulfill({contentType:'text/html',body:`<html><head><style>body{margin:0;background:#19252d}#app{position:absolute;inset:0}</style></head><body><div id="app"></div><script type="module">
import {WorldMap} from '/src/worldmap.ts';import {Terrain} from '/src/terrain.ts';import * as THREE from '/node_modules/three/build/three.module.js';
if (!localStorage.getItem('voxelon.waypoints')) localStorage.setItem('voxelon.waypoints',JSON.stringify([{x:120,z:-140,name:'Old base',color:0xe6b85c}]));
window.map=new WorldMap(new THREE.Scene(),new THREE.PerspectiveCamera(),new Terrain(42),{player:()=>({x:0,z:0,yaw:.4}),faction:()=>0});window.map.show();window.tick=setInterval(()=>window.map.update(),50);
</script></body></html>`}));
await page.goto(`${process.env.TEST_URL ?? 'http://127.0.0.1:5178'}/atlas-check`);
await page.getByRole('heading',{name:'World atlas'}).waitFor();
await page.getByRole('button',{name:'+ Mark my location'}).click();
await page.locator('input[name=name]').fill('Mountain camp');
await page.locator('input[name=color]').fill('#76dfcf');
await page.getByRole('button',{name:'Create waypoint'}).click();
assert.equal(await page.locator('.atlas-card').count(),2);
assert.match(await page.locator('.is-tracked').innerText(),/Mountain camp/);
await page.locator('[data-edit="1"]').click();
await page.locator('input[name=name]').fill('Home <safe>');
await page.getByRole('button',{name:'Save changes'}).click();
assert.match(await page.locator('.is-tracked').innerText(),/Home <safe>/);
await page.locator('[data-eye="1"]').click();
assert.equal(await page.locator('[data-eye="1"]').innerText(),'Hidden');
await page.locator('[data-track="1"]').click();
assert.equal(await page.locator('[data-eye="1"]').innerText(),'Visible');
await page.getByRole('searchbox').fill('old');assert.equal(await page.locator('.atlas-card').count(),1);
await page.getByRole('searchbox').fill('');
await page.locator('canvas').click({position:{x:200,y:150}});
await page.getByRole('button',{name:'Cancel waypoint'}).click();assert.equal(await page.locator('.atlas-card').count(),2);
await page.getByRole('button',{name:'Full world',exact:true}).click();
await page.screenshot({path:process.env.MAP_DESKTOP_SCREENSHOT ?? '/tmp/atlas-desktop.png'});
await page.locator('[data-del="0"] svg').click();assert.equal(await page.locator('.atlas-card').count(),1);
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('voxelon.waypoints')).length),1);
await page.reload();
await page.locator('.is-tracked').waitFor();
assert.match(await page.locator('.is-tracked').innerText(),/Home <safe>/);
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Heartland',exact:true}).click();
await page.screenshot({path:process.env.MAP_MOBILE_SCREENSHOT ?? '/tmp/atlas-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.querySelector('.atlas-panel').scrollWidth<=document.querySelector('.atlas-panel').clientWidth+1));
await page.getByRole('button',{name:'Close map'}).click();assert.equal(await page.evaluate(()=>window.map.open),false);
assert.deepEqual(errors,[]);console.log('PASS: legacy loading, create, edit, color, visibility, tracking, search, cancel, view switch, nested-icon delete, persistence, mobile overflow, close; no browser errors.');
await browser.close();
